<a href="https://colab.research.google.com/github/CodexJoe/Tutorial/blob/main/GMC_ARRAY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
'''Write a Python program to convert an array to an ordinary list with the same items.'''


import numpy as np

My_arry = np.array([[1,2,3,4], [5,6,7,8]])
My_List = list(My_arry)
print(type(My_List))

<class 'list'>


In [10]:
'''Write a NumPy program to compute the sum of the diagonal element of a given array.'''

import numpy as np
import random

My_Array = np.random.randint(1,7, size = (4,4))
print(My_Array)
My_Diag = My_Array[[0,1,2,3], [0,1,2,3]]
print(My_Diag)
print(np.sum(My_Diag))



[[6 3 2 2]
 [1 6 4 6]
 [5 4 3 1]
 [4 4 6 4]]
[6 6 3 4]
19


In [23]:
'''Given an array of your choice, get all the values higher than 
X :if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2.'''

import numpy as np
import random

AY = np.random.randint(1,7, size = (4,4))
print(AY)
X = AY[1,2]
print(X)
Filter = AY[AY>X]
print(Filter )

[[1 1 3 3]
 [2 2 2 5]
 [3 3 1 5]
 [1 3 6 2]]
2
[3 3 5 3 3 5 3 6]


In [25]:
'''Given two arrays A&B having the same shape. The task is to apply addition of A and B : C is the new array. '''

import numpy as np
import random

A = np.random.randint(1,7, size = (4,4))
B = np.random.randint(7, 30, size = (4,4))
print('This is the First Array A: ', A)
print('This is the First Array B: ', B)
C = A+B
print('This is the result of the summation of A and B: ', C)

This is the First Array A:  [[3 1 1 3]
 [2 4 2 5]
 [5 4 3 5]
 [4 4 5 1]]
This is the First Array B:  [[20 22 12 22]
 [22 19 25  9]
 [18 15 14 25]
 [20 17 11 29]]
This is the result of the summation of A and B:  [[23 23 13 25]
 [24 23 27 14]
 [23 19 17 30]
 [24 21 16 30]]
